### PR TITLE
Using full cert chain over single certificate

### LINKED ISSUE #156: Intermediate cert not being sent
It seems that the R3/Let's encrypt intermediate cert is not being sent from the server.

I have everything working OK via a web browser or command-line tools on macOS, but if I try to access the site with `curl` from Debian 10 I get the following error:

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Adding the `-k` option makes it work, of course.

When I've manually used CertBot in the past, there has been a "full-chain" cert and I suspect that acme4j is not generating it or micronaut-acme is not using it.

I believe this page is relevant: https://community.letsencrypt.org/t/curl-does-not-trust-le-certs-on-plain-debian/54091

I'm not 100% sure I've diagnosed this correctly, but I thought I'd open an issue anyway, because I'm 90% sure.

### PR DESCRIPTION
**Pull request by zendern**
Fixes #156 and #73 

Found that we were parsing the cert using
CertificateFactory.getCertificate. This was not giving us the full chain
but instead just the domain cert. Which in most places work but not in
all.

To address this we now will get the full chain using
CertificateFactor.getCertificates and pass that on the event to Netty so
that it can be used for initialization.

### CODE REVIEW

File: acme/src/main/java/io/micronaut/acme/services/AcmeService.java [hunk 1]
```diff
@@ -138,6 +140,23 @@ public X509Certificate getCurrentCertificate() {
         }
     }
 
+    protected X509Certificate[] getFullCertificateChain() {
+        try {
+            CertificateFactory cf = CertificateFactory.getInstance("X.509");
+            File certificate = new File(certLocation, DOMAIN_CRT);
+            if (certificate.exists()) {
+                return cf.generateCertificates(Files.newInputStream(certificate.toPath())).toArray(new X509Certificate[0]);
```
Comment (zendern) [inline acme/src/main/java/io/micronaut/acme/services/AcmeService.java:148]: Important change was to call `cf.generateCertificates` here and then pass this into the `CertificateEvent` and thus into Netty for initialization.

File: acme/src/main/java/io/micronaut/acme/events/CertificateEvent.java [hunk 2]
```diff
@@ -24,6 +24,7 @@
 public class CertificateEvent {
     private final X509Certificate certificate;
```
Comment (michaelkoetter) [inline acme/src/main/java/io/micronaut/acme/events/CertificateEvent.java:25]: Is this still required, ie. should there be a distinction between "single certificate" and "certificate chain"? 
The "single certificate" code path is only used for tls-apln-01 validation, but this could also utilize the `fullCertificateChain` array (just with a single entry).

Comment (zendern) [reply acme/src/main/java/io/micronaut/acme/events/CertificateEvent.java:25]: Yah thats fair. I left it due to the CertificateEvent constructor is public so in theory someone could be using it. But yes implementation wise I could just store the full chain and in the validation cert case an array of 1 instead of 2 objects.

**Comment by yawkat** [comment]
@zendern is there a reason this is still a draft? I would like to merge it, I see no obvious issues.

**Comment by zendern** [comment]
> @zendern is there a reason this is still a draft? I would like to merge it, I see no obvious issues.

After rebasing I remember now. CI tests were broken bit worked locally. Getting into trying to figure out why. Hoping to get it figured out this week so we can get this merged

**Review by yawkat — APPROVED** [review]

File: acme/src/main/java/io/micronaut/acme/events/CertificateEvent.java [hunk 3]
```diff
@@ -22,27 +22,42 @@
  * Event used to alert when a new ACME certificate is ready for use.
  */
 public class CertificateEvent {
-    private final X509Certificate certificate;
     private final KeyPair domainKeyPair;
+    private final X509Certificate[] fullCertificateChain;
     private boolean validationCert;
 
     /**
+     * @deprecated See constructor that takes full certificate chain instead.
```
Comment (sdelamo) [inline acme/src/main/java/io/micronaut/acme/events/CertificateEvent.java:30]: I think you can use something like this in the javadoc: 

`@deprecated {@link #CertificateEvent(KeyPai, boolean,X509Certificate)} instead.`

File: acme/src/test/groovy/io/micronaut/acme/AcmeCertRefresherMultiDomainsTaskSpec.groovy [hunk 4]
```diff
@@ -52,13 +52,17 @@ class AcmeCertRefresherMultiDomainsTaskSpec extends AcmeBaseSpec {
...
+                    certs.length == 2
                     def cert = (X509Certificate) certs[0]
                     cert.getIssuerDN().getName().contains("Pebble Intermediate CA")
                     cert.getSubjectDN().getName().contains(EXPECTED_DOMAIN)
                     cert.getSubjectAlternativeNames().size() == 2
                     cert.getSubjectAlternativeNames().collect({d-> d.get(1)}).contains(EXPECTED_DOMAIN)
                     cert.getSubjectAlternativeNames().collect({d-> d.get(1)}).contains(EXPECTED_ACME_DOMAIN)
+
+                    def cert2 = (X509Certificate) certs[1]
+                    cert2.getIssuerDN().getName().contains("Pebble Root CA")
```
Comment (sdelamo) [inline acme/src/test/groovy/io/micronaut/acme/AcmeCertRefresherMultiDomainsTaskSpec.groovy:64]: In groovy you can be more idiomatic by rewriting this:

`cert2.getIssuerDN().getName().contains("Pebble Root CA")`

as: 

`cert2.issuerDN.name.contains("Pebble Root CA")`

File: acme/src/test/groovy/io/micronaut/acme/AcmeCertRefresherMultiDomainsTaskSpec.groovy [hunk 5]
```diff
@@ -52,13 +52,17 @@ class AcmeCertRefresherMultiDomainsTaskSpec extends AcmeBaseSpec {
...
+                    cert2.getSubjectDN().getName().contains("Pebble Intermediate CA")
```
Comment (sdelamo) [inline acme/src/test/groovy/io/micronaut/acme/AcmeCertRefresherMultiDomainsTaskSpec.groovy:65]: In groovy, you can be more idiomatic by rewriting this:

`cert2.getSubjectDN().getName().contains("Pebble Intermediate CA")`

as: 

`cert2.subjectDN.name.contains("Pebble Intermediate CA")`

**Review by sdelamo — CHANGES_REQUESTED** [review]
It looks good. A couple of minor things.

File: acme/src/main/java/io/micronaut/acme/services/AcmeService.java [hunk 6]
```diff
@@ -138,6 +138,28 @@ public X509Certificate getCurrentCertificate() {
         }
     }
 
+    /**
+     * Returns the full certificate chain.
+     *
+     * @return array of each of the certificates in the chain
+     */
+    protected X509Certificate[] getFullCertificateChain() {
```
[the remark this answers is not in the document]
Comment (yawkat) [reply acme/src/main/java/io/micronaut/acme/services/AcmeService.java:146]: this should never be null

[the remark this answers is not in the document]
Comment (zendern) [reply acme/src/main/java/io/micronaut/acme/services/AcmeService.java:146]: Actually it can in the exceptional case right now. Thinking that should change and make it so that it never can be null.

File: acme/src/main/java/io/micronaut/acme/events/CertificateEvent.java (hunk 3 above)
Comment (zendern) [reply acme/src/main/java/io/micronaut/acme/events/CertificateEvent.java]: Fixed here [84db7da](https://github.com/micronaut-projects/micronaut-acme/pull/161/commits/84db7da34769c2c6423db67454f9482ef2b59c4b)

File: acme/src/main/java/io/micronaut/acme/services/AcmeService.java [hunk 7]
```diff
@@ -138,6 +138,28 @@ public X509Certificate getCurrentCertificate() {
...
+        try {
+            CertificateFactory cf = CertificateFactory.getInstance("X.509");
```
[the remark this answers is not in the document]
Comment (zendern) [reply acme/src/main/java/io/micronaut/acme/services/AcmeService.java]: Done here [16b05b6](https://github.com/micronaut-projects/micronaut-acme/pull/161/commits/16b05b6e8c8bbd5488dbbed41345b60c623ffbd5)

File: acme/src/main/java/io/micronaut/acme/services/AcmeService.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (zendern) [reply acme/src/main/java/io/micronaut/acme/services/AcmeService.java:147]: Made it so that even the exception case returns an empty array. [e960455](https://github.com/micronaut-projects/micronaut-acme/pull/161/commits/e96045515e7a2ff8239505cbe82abd2435e8983f)

File: acme/src/test/groovy/io/micronaut/acme/AcmeCertRefresherMultiDomainsTaskSpec.groovy [hunk 8]
```diff
@@ -52,13 +52,17 @@ class AcmeCertRefresherMultiDomainsTaskSpec extends AcmeBaseSpec {
...
-                    certs.length == 1
+                    certs.length == 2
                     def cert = (X509Certificate) certs[0]
                     cert.getIssuerDN().getName().contains("Pebble Intermediate CA")
                     cert.getSubjectDN().getName().contains(EXPECTED_DOMAIN)
                     cert.getSubjectAlternativeNames().size() == 2
                     cert.getSubjectAlternativeNames().collect({d-> d.get(1)}).contains(EXPECTED_DOMAIN)
                     cert.getSubjectAlternativeNames().collect({d-> d.get(1)}).contains(EXPECTED_ACME_DOMAIN)
+
+                    def cert2 = (X509Certificate) certs[1]
```
[the remark this answers is not in the document]
Comment (zendern) [reply acme/src/test/groovy/io/micronaut/acme/AcmeCertRefresherMultiDomainsTaskSpec.groovy]: Using more types here [075cb6c](https://github.com/micronaut-projects/micronaut-acme/pull/161/commits/075cb6cd314f4d3d933115e453b9cad544a2c4b7)

File: acme/src/test/groovy/io/micronaut/acme/AcmeCertRefresherMultiDomainsTaskSpec.groovy (hunk 4 above)
Comment (zendern) [reply acme/src/test/groovy/io/micronaut/acme/AcmeCertRefresherMultiDomainsTaskSpec.groovy]: Grooy-ify things here [075cb6c](https://github.com/micronaut-projects/micronaut-acme/pull/161/commits/075cb6cd314f4d3d933115e453b9cad544a2c4b7)

File: acme/src/main/java/io/micronaut/acme/services/AcmeService.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (sdelamo) [reply acme/src/main/java/io/micronaut/acme/services/AcmeService.java:147]: Thanks, annotate with `@NonNull` now that it is never null.

[the remark this answers is not in the document]
Comment (zendern) [reply acme/src/main/java/io/micronaut/acme/services/AcmeService.java:149]: Added here [67394be](https://github.com/micronaut-projects/micronaut-acme/pull/161/commits/67394be7d076e149a7c4b43006f02457ce9850c7)

File: acme/src/main/java/io/micronaut/acme/services/AcmeService.java [hunk 9]
```diff
@@ -278,7 +303,7 @@ private boolean writeCombinedFile(Certificate certificate) {
                     try (BufferedWriter writer = Files.newBufferedWriter(domainCsr.toPath(), WRITE, CREATE, TRUNCATE_EXISTING)) {
                         certificate.writeCertificate(writer);
                     }
-                    eventPublisher.publishEvent(new CertificateEvent(getCurrentCertificate(), domainKeyPair, false));
+                    eventPublisher.publishEvent(new CertificateEvent(domainKeyPair, false, getFullCertificateChain()));
```
Comment (sdelamo) [inline acme/src/main/java/io/micronaut/acme/services/AcmeService.java:306]: if getFullCertificateChain returns an empty array, we should publish a the event. Since `CertificateEvent`  assumes a non empty array due to `CertificateEvent::getCert` where it gets the first certificate in the array. should we?

File: acme/src/main/java/io/micronaut/acme/services/AcmeService.java [hunk 10]
```diff
@@ -482,7 +507,7 @@ private void doChallengeSpecificSetup(Authorization auth, Challenge challenge) t
      * Setup the certificate that has been saved to disk and configures it for use.
      */
     public void setupCurrentCertificate() {
-        eventPublisher.publishEvent(new CertificateEvent(getCurrentCertificate(), getDomainKeyPair(), false));
+        eventPublisher.publishEvent(new CertificateEvent(getDomainKeyPair(), false, getFullCertificateChain()));
```
Comment (sdelamo) [inline acme/src/main/java/io/micronaut/acme/services/AcmeService.java:510]: if getFullCertificateChain returns an empty array, we should publish a the event. Since `CertificateEvent`  assumes a non empty array due to `CertificateEvent::getCert` where it gets the first certificate in the array. should we?

**Review by yawkat — APPROVED** [review]

**Comment by recursivecodes** [comment]
Can we try this build again? I'd really love to have this merged soon.

**Review by yawkat — DISMISSED** [review]

**Comment by yawkat** [comment]
I think the sonar CI is just broken. we can ignore it for the merge

**Comment by recursivecodes** [comment]
OK - who can do the merge @yawkat?

**Comment by yawkat** [comment]
just waiting for sergio to re-review this. I will handle the rest.

File: acme/src/main/java/io/micronaut/acme/services/AcmeService.java (hunk 10 above)
Comment (sdelamo) [reply acme/src/main/java/io/micronaut/acme/services/AcmeService.java]: Resolved via https://github.com/micronaut-projects/micronaut-acme/pull/161/commits/6a5dd4466aadfa3ee97dec776869d8940a036cdc

File: acme/src/main/java/io/micronaut/acme/services/AcmeService.java (hunk 9 above)
Comment (sdelamo) [reply acme/src/main/java/io/micronaut/acme/services/AcmeService.java]: Resolved via https://github.com/micronaut-projects/micronaut-acme/pull/161/commits/6a5dd4466aadfa3ee97dec776869d8940a036cdc

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
thanks for the pr @zendern I have change the method signature to return optional https://github.com/micronaut-projects/micronaut-acme/pull/161/commits/6a5dd4466aadfa3ee97dec776869d8940a036cdc to be on the safer side.

**Comment by recursivecodes** [comment]
I am receiving an exception now when trying `3.1.1.SNAPSHOT`:

https://github.com/micronaut-projects/micronaut-acme/issues/211

**Comment by recursivecodes** [comment]
Same issue with MN-ACME `3.1.0` on Micronaut `3.2.0`
